Ashraf project week-2
HackYourHomework/React-class38 pull request #3
Opened 2022-09-17 00:47 UTC by Ashraf-Alshashaa

2022-09-27 14:25 UTC, nick-barth requested changes

2022-09-27 14:25 UTC, nick-barth commented on week1/project/ecommerce/src/App.js
> +// link to show the app https://grand-bienenstitch-b51d26.netlify.app
still love it, this would usually go int he readme tho.

2022-09-27 14:25 UTC, nick-barth commented on week2/project/ecommerce/src/App.js
> +// link to show the app for week-2: https://dashing-bublanina-fbf9a3.netlify.app
please only submit one HW per PR.

2022-09-27 14:25 UTC, nick-barth commented on week2/project/ecommerce/src/Nav-bar.js
> +    useState({
not good, not good, every time one of these key value pairs change, the entire page will be rerendered.

2022-09-27 14:25 UTC, nick-barth commented on week2/project/ecommerce/src/Nav-bar.js
> +    (async () => {
cute, but not very readable, please declare a named function, and call it.

2022-09-27 14:25 UTC, nick-barth commented on week2/project/ecommerce/src/Nav-bar.js
> +  return checkReturn(isLoading, status, items, errorMassage);
You should really be returning JSX, this is difficult to read, as people don't know where the JSX in your component will be.

2022-09-27 14:25 UTC, nick-barth commented on week2/project/ecommerce/src/ProductDetails.js
> +  return checkReturn(isLoading, status, items, errorMassage);
same issue as the other component, looks like you copy pasted this, which is okay! but when you fix one, fix both.

2022-09-27 14:25 UTC, nick-barth commented on week2/project/ecommerce/src/Products.js
> +    ));
same issue again

2022-09-28 14:30 UTC, Ashraf-Alshashaa commented on week1/project/ecommerce/src/App.js
> +// link to show the app https://grand-bienenstitch-b51d26.netlify.app
thanks, I'm happy to hear that.
I forgot to move the link to the readme file.

2022-09-28 14:33 UTC, Ashraf-Alshashaa commented on week2/project/ecommerce/src/App.js
> +// link to show the app for week-2: https://dashing-bublanina-fbf9a3.netlify.app
Sorry it happened by mistake

2022-09-28 14:33 UTC, Ashraf-Alshashaa commented on week2/project/ecommerce/src/Nav-bar.js
> +    useState({
it's done

2022-09-28 14:34 UTC, Ashraf-Alshashaa commented on week2/project/ecommerce/src/Nav-bar.js
> +    (async () => {
it's done

2022-09-28 14:34 UTC, Ashraf-Alshashaa commented on week2/project/ecommerce/src/Nav-bar.js
> +  return checkReturn(isLoading, status, items, errorMassage);
it's done

2022-09-28 14:34 UTC, Ashraf-Alshashaa commented on week2/project/ecommerce/src/ProductDetails.js
> +  return checkReturn(isLoading, status, items, errorMassage);
it's done

2022-09-28 14:34 UTC, Ashraf-Alshashaa commented on week2/project/ecommerce/src/Products.js
> +    ));
it's done

2022-09-28 14:34 UTC, Ashraf-Alshashaa commented on week2/project/ecommerce/src/Nav-bar.js
> +      <button key={category} onClick={() => cb(category)}>
it's done

2023-02-07 14:11 UTC, closed without merging